### ISSUE TITLE
Loading And Completing A Custom Level Causes The Level Counter To Increase

### ISSUE THREAD

**Issue by JoeMeister007** [rpg7000/Monogame_Sokobon#3]
https://user-images.githubusercontent.com/81037234/122260129-e7901200-cea0-11eb-83bb-13fd1389dc28.mp4

**Comment by ElectricalHazards** [comment]
Issue should have have been fixed in [a7a8837](https://github.com/rpg7000/Monogame_Sokoban/commit/a7a883745dec1334406307e01d458133d32aed5e) along with #2
