### ISSUE TITLE
Pressing The Load Level Button And Cancelling Still Changes The Level Type To Custom

### ISSUE THREAD

**Issue by JoeMeister007** [rpg7000/Monogame_Sokobon#4]
https://user-images.githubusercontent.com/81037234/122260377-32118e80-cea1-11eb-8d32-b5b622a86837.mp4

**Comment by ElectricalHazards** [comment]
Issue should be fixed in commit [929ca75](https://github.com/rpg7000/Monogame_Sokoban/commit/929ca754e41506105f3dcbfa97c733bdca1a4359)
